<a href="https://colab.research.google.com/github/OfficerChul/learnpytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [80]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

### Creating tensors

In [81]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [82]:
scalar.ndim

0

In [83]:
# Get tensor back as Python int
scalar.item()

7

In [84]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [85]:
vector.ndim

1

In [86]:
vector.shape

torch.Size([2])

In [87]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [88]:
MATRIX.ndim

2

In [89]:
MATRIX.shape

torch.Size([2, 2])

In [90]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [91]:
TENSOR.ndim

3

In [92]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are important because the way neural networks learn is that they start swith tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> updata random numbers -> look at data ...`



In [93]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1643, 0.0627, 0.5738, 0.9913],
        [0.5057, 0.1172, 0.1923, 0.3432],
        [0.4624, 0.5402, 0.2346, 0.2705]])

In [94]:
random_tensor.ndim

2

In [95]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # hieght, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [96]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [97]:
# Create a tensors with all ones

In [98]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [99]:
ones.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### Creatung a range of tensors and tensors-like

In [100]:
# Use torch.range()
one_to_ten = torch.arange(1, 10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatype is one of the 3 big errors with Pytorch & deep learning.
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [102]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what deovice is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor.dtype

torch.float32

In [103]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [104]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [105]:
int_32_tensor = torch.tensor([3, 6, 8], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [106]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 72.])

 ### Getting information from tensors

 1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
 2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
 3. Tensros not on the right device - to get device from a tensor, can use `tensor.device`

In [107]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9964, 0.6828, 0.5612, 0.8288],
        [0.5483, 0.1182, 0.0967, 0.2676],
        [0.2940, 0.5090, 0.6645, 0.9918]])

In [108]:
# Find out details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device of tensor is on: {some_tensor.device}')

tensor([[0.9964, 0.6828, 0.5612, 0.8288],
        [0.5483, 0.1182, 0.0967, 0.2676],
        [0.2940, 0.5090, 0.6645, 0.9918]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [109]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [110]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [111]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [112]:
# Try out Pytorch in-built funtions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [113]:
torch.add(tensor, 1)

tensor([2, 3, 4])

### Matric multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
- `(3,2) @ (3,2)` wont work
- `(3,2) @ (2, 3)` will work
- `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
- `(2,3) @ (3,2)` -> `(2,2)`
- `(3,2) @ (2,3)` -> `(3,3)`


In [114]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f'Equals: {(tensor * tensor)}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [115]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [116]:
%%time
res = 0
for i in range(len(tensor)):
  res += tensor[i] * tensor[i]

res

CPU times: user 218 µs, sys: 0 ns, total: 218 µs
Wall time: 2.23 ms


tensor(14)

In [117]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 46 µs, sys: 0 ns, total: 46 µs
Wall time: 50.1 µs


tensor(14)

### One of the most common erros in deep learning: shape error

*이탤릭체 텍스트*

In [119]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7, 10],
                        [8, 11],
                        [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matmul)
torch.mm(tensor_A, tensor_B)

RuntimeError: ignored

To fix out tensor shape issues, we can manipulate the shape of one of out tensors using **transpose**.

A **transpose** switches the axes or dimensions of given tensor.

In [120]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [121]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [122]:
 tensor_A @ tensor_B.T

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [123]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [124]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [125]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [126]:
%%time
torch.min(x)

CPU times: user 29 µs, sys: 0 ns, total: 29 µs
Wall time: 49.4 µs


tensor(0)

In [127]:
%%time
x.min()

CPU times: user 34 µs, sys: 0 ns, total: 34 µs
Wall time: 37.7 µs


tensor(0)

## Finding the positional min and max

In [128]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [129]:
# Find the index in the tensor that has the minimum value
x.argmin()

tensor(0)

In [130]:
x[x.argmin()]

tensor(0)

In [131]:
# Find the index in the tensor that has the maximum value
x.argmax()

tensor(9)

In [132]:
x[x.argmax()]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

- Reshaping - reshapes an input tensor to a defined shape
- View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stackig - combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all `1` dimensions from a tensor
- Unsqueeze - add a `1` dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [133]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [134]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [135]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [136]:
# Changing z changes x (because a view of a tensor shares the same memory as x)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [137]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [138]:
# torch.squeeze().- removes all single dimensions from a target tensor
print(x_reshaped)
x_squeezed = x_reshaped.squeeze()
print(x_squeezed)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])


In [139]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(x_squeezed)
x_unsqueezed_zero = x_squeezed.unsqueeze(dim=0)
x_unsqueezed_one = x_squeezed.unsqueeze(dim=1)
print(x_unsqueezed_zero)
print(x_unsqueezed_one)

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [140]:
# torch.permute - rearranges the dimensions of a target rensor in a specified order
# permute function shares the memory
x = torch.rand(224, 224, 3) # [height, width, color_channels]

# Permute the orig tensor to rearragne the dim order
x_permuted = x.permute(2, 0, 1)
x.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [141]:
x[0, 0, 0] = 111
print(x[0, 0, 0], x_permuted[0, 0, 0])

tensor(111.) tensor(111.)


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indeing with NumPy

In [3]:
# Create a tensor
import torch

x = torch.arange(1, 10)
x = x.reshape(1, 3, 3)
print(x[0])
print(x[0, 0])
print(x[0, 0, 0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [4]:
# You can also use ":" to select "all" of the target dim
print(x[:, 0])

tensor([[1, 2, 3]])


In [5]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [6]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [7]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [8]:
# Index on x to return 9
print(x[:, 2, 2])
# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor([9])
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

- Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
- PyTorch tensor -> NumPy -> torch.Tensor.numpy()

NumPy's default dtype is `float64`.
Torch's default dtype is `float32`

In [9]:
import torch
import numpy as np

array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [13]:
temp = torch.tensor([1.,2.,3.])
temp.dtype, array.dtype

(torch.float32, dtype('float64'))

In [19]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [22]:
# Tensor to NumPy array
tensor = torch.ones(7)
print(tensor, tensor.dtype)
array = tensor.numpy()
print(array, array.dtype)

tensor([1., 1., 1., 1., 1., 1., 1.]) torch.float32
[1. 1. 1. 1. 1. 1. 1.] float32


In [25]:
tensor = torch.ones(7, dtype=torch.float64)
print(tensor, tensor.dtype)
array = tensor.numpy()
print(array, array.dtype)

# NumPy and Torch reflects the dtype interactively.

tensor([1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64) torch.float64
[1. 1. 1. 1. 1. 1. 1.] float64


## Reproducibility (trying to take random out of random)

Random Seed

In [26]:
# Compare randomly generated tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A == random_tensor_B)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [27]:
# Make some random but reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_torch_D = torch.rand(3, 4)

print(random_tensor_C == random_torch_D)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

### 1. Getting the GPU

In [29]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 2. Check for GPU access with PyTorch



In [1]:
import torch
print(torch.cuda.is_available())

False


In [2]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [3]:
# Count the number of devices
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on the GPU

In [5]:
# Create a tensor (default on the CPU)
tensor = torch.arange(1, 11, 2)

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 3, 5, 7, 9]) cpu


In [7]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 3, 5, 7, 9]), device(type='cpu'))

### 4. Moving tensors back to the CPU

In [8]:
# Cannot convert tensor on gpu to NumPy array
tensor_on_gpu.numpy()

array([1, 3, 5, 7, 9])

In [9]:
# To fix this issue, we need to move the tensor from GPU to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 3, 5, 7, 9])